import 'dart:typed_data';

import 'package:hive_flutter/hive_flutter.dart';
import 'package:qkomo_ui/features/profile/domain/entities/user_profile.dart';

/// Hive box initialization for UserProfile feature
class ProfileHiveBoxes {
  /// Box name for user profile storage
  static const String userProfile = 'user_profile_box';

  /// Initialize Hive boxes for UserProfile feature
  ///
  /// Registers the UserProfile adapter and opens the box with encryption.
  /// Called from main.dart during app initialization.
  static Future<void> init([Uint8List? encryptionKey]) async {
    // Register adapter (generated by build_runner)
    // TypeId 25 is used for UserProfile
    if (!Hive.isAdapterRegistered(25)) {
      Hive.registerAdapter(UserProfileImplAdapter());
    }

    final cipher = encryptionKey != null ? HiveAesCipher(encryptionKey) : null;

    // Open as dynamic box (stores UserProfile object + bool sync flag)
    await Hive.openBox<dynamic>(userProfile, encryptionCipher: cipher);
  }
}
