import 'package:hive/hive.dart';

/// DEPRECATED: Old Meal adapter (typeId: 5) - kept for migration only
/// Use MealV2Adapter (typeId: 6) auto-generated by Freezed for new code
@Deprecated(
    'Use MealV2Adapter (typeId: 6) instead. This is kept for migration only.')
class MealAdapterV1 extends TypeAdapter<dynamic> {
  @override
  final int typeId = 5;

  @override
  dynamic read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };

    // Return a Map representation of the old Meal format
    // This will be used by MealMigrationService to convert to new format
    return {
      'id': fields[0] as String,
      'userId': fields[1] as String,
      'name': fields[2] as String,
      'ingredients': (fields[3] as List).cast<String>(),
      'mealType': fields[4] as int,
      'scheduledFor': fields[5] as DateTime,
      'createdAt': fields[6] as DateTime,
      'updatedAt': fields[7] as DateTime?,
      'notes': fields[8] as String?,
      'photoPath': fields[9] as String?,
    };
  }

  @override
  void write(BinaryWriter writer, dynamic obj) {
    // Write should never be called for V1 adapter (read-only for migration)
    throw UnsupportedError('MealAdapterV1 is read-only for migration purposes');
  }
}
