// Mocks generated by Mockito 5.4.4 from annotations
// in qkomo_ui/test/features/sync/application/sync_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:connectivity_plus/connectivity_plus.dart' as _i6;
import 'package:connectivity_plus_platform_interface/connectivity_plus_platform_interface.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;
import 'package:qkomo_ui/features/entry/data/hybrid_entry_repository.dart'
    as _i2;
import 'package:qkomo_ui/features/entry/domain/entry.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [HybridEntryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHybridEntryRepository extends _i1.Mock
    implements _i2.HybridEntryRepository {
  @override
  bool get enableCloudSync => (super.noSuchMethod(
        Invocation.getter(#enableCloudSync),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  String get repositoryName => (super.noSuchMethod(
        Invocation.getter(#repositoryName),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#repositoryName),
        ),
        returnValueForMissingStub: _i3.dummyValue<String>(
          this,
          Invocation.getter(#repositoryName),
        ),
      ) as String);

  @override
  _i4.Future<List<_i5.Entry>> getEntries({
    DateTime? from,
    DateTime? to,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEntries,
          [],
          {
            #from: from,
            #to: to,
          },
        ),
        returnValue: _i4.Future<List<_i5.Entry>>.value(<_i5.Entry>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.Entry>>.value(<_i5.Entry>[]),
      ) as _i4.Future<List<_i5.Entry>>);

  @override
  _i4.Future<_i5.Entry?> getEntryById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getEntryById,
          [id],
        ),
        returnValue: _i4.Future<_i5.Entry?>.value(),
        returnValueForMissingStub: _i4.Future<_i5.Entry?>.value(),
      ) as _i4.Future<_i5.Entry?>);

  @override
  _i4.Future<void> saveEntry(_i5.Entry? entry) => (super.noSuchMethod(
        Invocation.method(
          #saveEntry,
          [entry],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteEntry(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteEntry,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<List<_i5.Entry>> watchEntries() => (super.noSuchMethod(
        Invocation.method(
          #watchEntries,
          [],
        ),
        returnValue: _i4.Stream<List<_i5.Entry>>.empty(),
        returnValueForMissingStub: _i4.Stream<List<_i5.Entry>>.empty(),
      ) as _i4.Stream<List<_i5.Entry>>);

  @override
  _i4.Future<void> sync() => (super.noSuchMethod(
        Invocation.method(
          #sync,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<int> getPendingSyncCount() => (super.noSuchMethod(
        Invocation.method(
          #getPendingSyncCount,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
        returnValueForMissingStub: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);
}

/// A class which mocks [Connectivity].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivity extends _i1.Mock implements _i6.Connectivity {
  @override
  _i4.Stream<List<_i7.ConnectivityResult>> get onConnectivityChanged =>
      (super.noSuchMethod(
        Invocation.getter(#onConnectivityChanged),
        returnValue: _i4.Stream<List<_i7.ConnectivityResult>>.empty(),
        returnValueForMissingStub:
            _i4.Stream<List<_i7.ConnectivityResult>>.empty(),
      ) as _i4.Stream<List<_i7.ConnectivityResult>>);

  @override
  _i4.Future<List<_i7.ConnectivityResult>> checkConnectivity() =>
      (super.noSuchMethod(
        Invocation.method(
          #checkConnectivity,
          [],
        ),
        returnValue: _i4.Future<List<_i7.ConnectivityResult>>.value(
            <_i7.ConnectivityResult>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i7.ConnectivityResult>>.value(
                <_i7.ConnectivityResult>[]),
      ) as _i4.Future<List<_i7.ConnectivityResult>>);
}
