// Mocks generated by Mockito 5.4.4 from annotations
// in qkomo_ui/test/features/entry/data/hybrid_entry_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:qkomo_ui/features/capture/domain/capture_result.dart' as _i5;
import 'package:qkomo_ui/features/entry/data/local_entry_repository.dart'
    as _i2;
import 'package:qkomo_ui/features/entry/data/remote_entry_repository.dart'
    as _i6;
import 'package:qkomo_ui/features/entry/domain/entry.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [LocalEntryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalEntryRepository extends _i1.Mock
    implements _i2.LocalEntryRepository {
  @override
  _i3.Future<void> saveEntry(_i4.Entry? entry) => (super.noSuchMethod(
        Invocation.method(
          #saveEntry,
          [entry],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i4.Entry? getEntryById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getEntryById,
          [id],
        ),
        returnValueForMissingStub: null,
      ) as _i4.Entry?);

  @override
  _i3.Future<void> deleteEntry(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteEntry,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  List<_i4.Entry> getAllEntries() => (super.noSuchMethod(
        Invocation.method(
          #getAllEntries,
          [],
        ),
        returnValue: <_i4.Entry>[],
        returnValueForMissingStub: <_i4.Entry>[],
      ) as List<_i4.Entry>);

  @override
  List<_i4.Entry> getPendingEntries() => (super.noSuchMethod(
        Invocation.method(
          #getPendingEntries,
          [],
        ),
        returnValue: <_i4.Entry>[],
        returnValueForMissingStub: <_i4.Entry>[],
      ) as List<_i4.Entry>);

  @override
  _i3.Stream<List<_i4.Entry>> watchEntries() => (super.noSuchMethod(
        Invocation.method(
          #watchEntries,
          [],
        ),
        returnValue: _i3.Stream<List<_i4.Entry>>.empty(),
        returnValueForMissingStub: _i3.Stream<List<_i4.Entry>>.empty(),
      ) as _i3.Stream<List<_i4.Entry>>);

  @override
  _i3.Future<void> migrateFromCaptureResult(_i5.CaptureResult? result) =>
      (super.noSuchMethod(
        Invocation.method(
          #migrateFromCaptureResult,
          [result],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [RemoteEntryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteEntryRepository extends _i1.Mock
    implements _i6.RemoteEntryRepository {
  @override
  _i3.Future<List<_i4.Entry>> fetchEntries({
    DateTime? from,
    DateTime? to,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchEntries,
          [],
          {
            #from: from,
            #to: to,
          },
        ),
        returnValue: _i3.Future<List<_i4.Entry>>.value(<_i4.Entry>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.Entry>>.value(<_i4.Entry>[]),
      ) as _i3.Future<List<_i4.Entry>>);

  @override
  _i3.Future<void> pushEntry(_i4.Entry? entry) => (super.noSuchMethod(
        Invocation.method(
          #pushEntry,
          [entry],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteEntry(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteEntry,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
